import { StyleSheet } from 'react-native';
import { Fonts } from '../../android/app/src/constants/fonts';

export const AmazeMe_Styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#FFF',
      padding: 10,
    },
    darkContainer: {
      flex: 1,
      backgroundColor: '#121212',
      padding: 10,
    },
    PoemText: {
      fontFamily: Fonts.NotoSerif.Regular,
      fontSize: 19,
      color: 'black',
      textAlign: 'center',
      lineHeight: 26,
    },
    darkPoemText: {
      fontFamily: Fonts.NotoSerif.Regular,
      fontSize: 19,
      color: 'white',
      textAlign: 'center',
      lineHeight: 26,
    },
    PoemTextContainer: {
      backgroundColor: '#FFFFFF',
      padding: 20,
      elevation: 5,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 5,
      },
      flexGrow: 1,
      marginBottom: 10,
    },
    darkPoemTextContainer: {
      backgroundColor: '#121212',
      padding: 20,
      elevation: 5,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 5,
      },
      flexGrow: 1,
      marginBottom: 10,
    },
    allButtonsContainer: {
      marginTop: 10,
      paddingBottom: 10,
    },
    buttonContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 10,
      paddingLeft: 10,
      paddingRight: 10,
      marginBottom: 15,
    },
    buttonText: {
      fontFamily: Fonts.NotoSerif.Regular,
      color: 'black',
      fontSize: 17,
      textAlign: 'center',
    },
    darkButtonText: {
      fontFamily: Fonts.NotoSerif.Regular,
      color: 'white',
      fontSize: 17,
      textAlign: 'center',
    },
    fontSizeButton: {
      flex: 1,
      height: 40,
      fontSize: 19,
      padding: 5,
      borderRadius: 5,
      alignItems: 'center',
      backgroundColor: 'white',
      justifyContent: 'center',
      marginHorizontal: 5,
      elevation: 5,
    },
    darkFontSizeButton: {
      flex: 1,
      height: 40,
      fontSize: 19,
      padding: 5,
      borderRadius: 5,
      alignItems: 'center',
      backgroundColor: '#1f1f1f',
      justifyContent: 'center',
      marginHorizontal: 5,
      elevation: 5,
    },
    getNewPoemButton: {
      backgroundColor: '#1F1F1F',
      padding: 12,
      borderRadius: 8,
      alignItems: 'center',
      alignSelf: 'center',
      width: 370,
      marginTop: -2,
    },
    darkGetNewPoemButton: {
      backgroundColor: '#43464b',
      padding: 12,
      borderRadius: 8,
      alignItems: 'center',
      alignSelf: 'center',
      width: 370,
      marginTop: -2,
    },
    getNewPoemButtonText: {
      fontFamily: Fonts.NotoSerif.Regular,
      color: 'white',
      fontSize: 20,
    },
    darkGetNewPoemButtonText: {
      fontFamily: Fonts.NotoSerif.Regular,
      color: 'white',
      fontSize: 20,
    },
    savedPoemButton: {
      padding: 8,
      borderRadius: 30,
      minWidth: 30,
      paddingLeft: 10,
      right: 10,
    },
  });