import { StyleSheet } from 'react-native';
import { Fonts } from '../../android/app/src/constants/fonts';

export const MainPage_Styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#ffffff',
      flexDirection: 'column',
    },
    darkContainer: {
      flex: 1,
      backgroundColor: '#121212',
      flexDirection: 'column',
    },
    headerContainer: {
      padding: 20,
      paddingTop: 30,
      paddingBottom: 30,
      alignItems: 'center',
      backgroundColor: '#f8f8f8',
      borderBottomWidth: 1,
      borderBottomColor: '#e0e0e0',
    },
    darkHeaderContainer: {
      padding: 20,
      paddingTop: 30,
      paddingBottom: 30,
      alignItems: 'center',
      backgroundColor: '#1a1a1a',
      borderBottomWidth: 1,
      borderBottomColor: '#333333',
    },
    headerTitle: {
      fontFamily: Fonts.NotoSerif.Regular,
      fontSize: 32,
      color: '#1e1e1e',
      textAlign: 'center',
      fontWeight: 'bold',
    },
    darkHeaderTitle: {
      fontFamily: Fonts.NotoSerif.Regular,
      fontSize: 32,
      color: '#f0f0f0',
      textAlign: 'center',
      fontWeight: 'bold',
    },
    menuContainer: {
      flex: 1,
      padding: 16,
      justifyContent: 'center',
      gap: 16,
    },
    button: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 16,
      padding: 20,
      marginVertical: 6,
      backgroundColor: '#ffffff',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.08,
      shadowRadius: 3,
      elevation: 2,
    },
    darkButton: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#1f1f1f',
      borderRadius: 16,
      padding: 20,
      marginVertical: 6,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.15,
      shadowRadius: 3,
      elevation: 2,
    },
    buttonText: {
      fontFamily: Fonts.NotoSerif.Regular,
      color: '#1e1e1e',
      fontSize: 28,
      textAlign: 'center',
      marginBottom: 8,
    },
    darkButtonText: {
      fontFamily: Fonts.NotoSerif.Regular,
      color: '#f0f0f0',
      fontSize: 28,
      textAlign: 'center',
      marginBottom: 8,
    },
    buttonDescription: {
      fontFamily: Fonts.NotoSerif.Regular,
      color: '#666666',
      fontSize: 14,
      textAlign: 'center',
    },
    darkButtonDescription: {
      fontFamily: Fonts.NotoSerif.Regular,
      color: '#a0a0a0',
      fontSize: 14,
      textAlign: 'center',
    },
    touchable_Poems: {
      flex: 1,
      backgroundColor: '#ffffff',
      //     borderBottomWidth: 3,
      //     borderColor: "gold",
    },
    darkTouchable_Poems: {
      flex: 1,
      backgroundColor: '#1f1f1f',
    },
    touchable_AmazeMe: {
      flex: 1,
      backgroundColor: '#ffffff',
    },
    darkTouchable_AmazeMe: {
      flex: 1,
      backgroundColor: '#1f1f1f',
    },
  });