import { StyleSheet } from 'react-native';
import { Fonts } from '../../android/app/src/constants/fonts';

export const PoemDetail_Styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  darkContainer: {
    flex: 1,
    backgroundColor: '#121212',
  },
  PoemText: {
    fontSize: 19,
    color: 'black',
    fontFamily: Fonts.NotoSerif.Regular,
    textAlign: 'center',
    lineHeight: 26,
  },
  darkPoemText: {
    fontSize: 19,
    color: 'white',
    fontFamily: Fonts.NotoSerif.Regular,
    textAlign: 'center',
    lineHeight: 26,
  },
  PoemTextContainer: {
    backgroundColor: '#FFFFFF',
    padding: 20,
    shadowOffset: { width: 0, height: 5 },
    flexGrow: 1,
  },
  darkPoemTextContainer: {
    backgroundColor: '#121212',
    padding: 20,
    shadowOffset: { width: 0, height: 5 },
    flexGrow: 1,
  },
  fontSizeButton: {
    flex: 1,
    height: 50,
    fontSize: 19,
    padding: 5,
    borderRadius: 5,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 3,
    backgroundColor: 'white',
    justifyContent: 'center',
    marginHorizontal: 5,
    elevation: 5,
  },
  darkFontSizeButton: {
    flex: 1,
    height: 50,
    fontSize: 19,
    padding: 5,
    borderRadius: 5,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 3,
    backgroundColor: '#1f1f1f',
    justifyContent: 'center',
    marginHorizontal: 5,
    elevation: 5,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    gap: 0,
    paddingLeft: 10,
    paddingRight: 10,
  },
  buttonText: {
    color: 'black',
    fontSize: 17,
    fontFamily: Fonts.NotoSerif.Regular,
    textAlign: 'center',
  },
  darkButtonText: {
    color: 'white',
    fontSize: 17,
    fontFamily: Fonts.NotoSerif.Regular,
    textAlign: 'center',
  },
  savedPoemButton: {
    padding: 8,
    borderRadius: 30,
    minWidth: 30,
    paddingLeft: 10,
    right: 10,
  },
});